alter session set "_oracle_script"=true;

create user DCSLR identified by 1234;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO DCSLR;
ALTER USER DCSLR DEFAULT TABLESPACE USERS;
ALTER USER DCSLR TEMPORARY TABLESPACE TEMP;